#
# This software is released under the BSD License, see LICENSE.
#

include ../mk/base.mk
include ../mk/compress.mk
include ../mk/hash.mk
include ../mk/network.mk
include ../mk/pthread.mk
include ../mk/prog.mk
