.\"
.\" This software is released under the BSD License, see LICENSE.
.\"
.Dd Apr 10, 2004
.Dt CVSYNC2CVSUP 1
.Os
.Sh NAME
.Nm cvsync2cvsup
.Nd convert a scanfile from the cvsync style to the CVSup style.
.Sh SYNOPSIS
.Nm cvsync2cvsup
.Op Fl hqv
.Op Fl g Ar group
.Op Fl u Ar user
.Fl i Ar cvsync-scanfile
.Fl o Ar CVSup-scanfile
.Sh DESCRIPTION
.Nm
converts a cvsync scanfile into a CVSup(R) counterpart, has been added.
When the upstream server is using CVSync and you want to redistribute the
contents using CVSup, this tool is your friend.
.Pp
The following options are available:
.Bl -tag -width indent
.It Fl g Ar group
Forces
.Nm
to use a group name of
.Ar group .
.It Fl h
Print the usage of
.Nm
to standard error.
.It Fl i Ar cvsync-scanfile
Specifies an input file name.
.It Fl o Ar CVSup-scanfile
Specifies an output file name.
.It Fl q
Be silent mode.
.It Fl u Ar user
Forces
.Nm
to use a user name of
.Ar user .
.It Fl v
Be verbose mode.
.El
.Sh EXIT STATUS
The
.Nm
utility exits EXIT_SUCCESS on success, and EXIT_FAILURE if an error occurs.
.Sh SEE ALSO
.Xr cvscan 1 ,
.Xr cvsup2cvsync 1 ,
.Xr cvsyncd 1
