#
# This software is released under the BSD License, see LICENSE.
#

PROG	= cvsync2cvsup
SRCS	= attribute_rcs.c cvsync.c list.c logmsg.c mdirent.c mdirent_rcs.c \
	  scanfile.c scanfile_rcs.c \
	  cvsup.c intr.c main.c

include ../mk/base.mk
include ../mk/pthread.mk
include ../mk/prog.mk
