#
# This software is released under the BSD License, see LICENSE.
#

PROG	= rcscmp
SRCS	= hash.c rcslib.c main.c

include ../mk/base.mk
include ../mk/hash.mk
include ../mk/pthread.mk
include ../mk/prog.mk
