.\"
.\" This software is released under the BSD License, see LICENSE.
.\"
.Dd Oct 27, 2003
.Dt RCSCMP 1
.Os
.Sh NAME
.Nm rcscmp
.Nd compare files as
.Xr rcsfile 5
compliant
.Sh SYNOPSIS
.Nm rcscmp
.Ar file1 file2
.Sh DESCRIPTION
.Nm
examine that two files are idential as
.Xr rcsfile 5
compliant.
.Sh EXIT STATUS
The
.Nm
utility exits EXIT_SUCCESS on success, and EXIT_FAILURE if an error occurs.
.Sh SEE ALSO
.Xr rcsfile 5
