.\"
.\" Copyright (c) 2003-2005 MAEKAWA Masahide <maekawa@cvsync.org>
.\"                         Hiroki Sato <hrs@allbsd.org>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the author nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd Jun 23, 2005
.Dt CVSYNC 1
.Os
.Sh NAME
.Nm cvsync
.Nd synchronize CVS repositories
.Sh SYNOPSIS
.Nm cvsync
.Op Fl 46LVZhqvz
.Op Fl c Ar file
.Op Fl p Ar file
.Op Ar URI ...
.Sh DESCRIPTION
.Nm
is a fast, portable, IPv6 capable CVS repository synchronization utility.
.Nm
consists of a client program
.Nm ,
a server program
.Nm cvsyncd ,
a supplemental tool
.Nm cvscan ,
.Nm cvsup2cvsync ,
and,
.Nm cvsync2cvsup .
.Pp
.Nm
retrieves CVS repository tree(s), which is called
.Ql collections
on the remote host where
.Nm cvsyncd
is running, and creates/updates the local mirror of them.
The update algorithm allows to transfer just differences between sets of files
across the network link, using cryptographic hash function and so on.
.Pp
The following options are available:
.Bl -tag -width indent
.It Fl 4
Forces
.Nm
to use IPv4 addresses only.
.It Fl 6
Forces
.Nm
to use IPv6 addresses only.
.It Fl L
Forces
.Nm
to set
.Ql errormode
to
.Ql fixup
for all collections.
.It Fl V
Print the version number of
.Nm
to standard error.
.It Fl Z
Disables a compression.
.It Fl c Ar file
Specifies the file to store configurations and collections.
.It Fl h
Print the location of the default configuration file, the protocol revision
number, the version number of
.Nm ,
and the usage to standard error.
.It Fl p Ar file
Specifies the file to store a pid number.
.It Fl q
Be silent mode.
.It Fl v
Be verbose mode.
.It Fl z
Enables a compression.
.El
.Sh CONFIGURATION FILE
.Nm
uses a configuration file which specifies the remote host(s) and collections
to be updated.
Basically it is a free format plain text file whose keywords are separated by
white space(s) and/or carriage return(s).
Comments begin with
.Ql #
and extend to the end of the line.
.Pp
The following keywords are available:
.Bl -tag -width indent
.It Sy base Ar directory
Specifies a prefix used for relative pathnames in all of the keyword
.Ql refuse
and
.Ql scanfile .
It must be an absolute path.
This keyword is valid in
.Ql config .
.It Sy base-prefix Ar directory
Specifies a prefix used for relative pathnames in all of the keyword
.Ql prefix .
It must be an absolute path.
This keyword is valid in
.Ql config .
.It Sy collection "{ ... }"
Specifies a collection to be updated.
The keywords and parameters that are included in the succeeding braces are
used to specify the collection name, the local path where the collection is
stored, and so on.
.It Sy compress
Enables a compression.
This keyword is valid in
.Ql config .
.It Sy config "{ ... }"
Defines a session with the keywords and parameters in the succeeding braces.
A
.Ql config
has a
.Ql hostname
and a
.Ql port
number of a remote host, and one or more
.Ql collection
to be updated.
.Nm
processes every
.Ql config
of the configuration file in due order.
A nest of
.Ql config
is not allowed.
.It Sy errormode Ar mode
Specifies the behavior when any potential errors/conflicts are found in local
distributions.
.Pp
The following modes are available:
.Bl -tag -width indent
.It Sy abort
Exit with error messages immediately.
.It Sy fixup
Recover errors/conflicts and keep running.
.It Sy ignore
Ignore any errors/conflicts.
.El
.Pp
The default value is
.Ql abort .
This keyword is valid in
.Ql collection .
.It Sy hash Ar type
Specifies the hash type that
.Nm
uses to verify files and deltas transferred during a synchronization.
.Ql md5
shall be supported in any environments.
.Ql ripemd160 ,
.Ql sha1 ,
.Ql tiger192
and, any other types are optional.
The default value is
.Ql md5 .
This keyword is valid in
.Ql config .
.It Sy host, hostname Ar hostname
Specifies the remote host name.
This keyword is valid in
.Ql config .
.It Sy loose
Obsoleted.
Same to set
.Ql errormode
to
.Ql ignore .
.It Sy name Ar name
Specifies a collection name to be updated.
.Ql all
is a special name that can be used with
.Ql release list
to fetch a list of available collections from the remote host.
See also
.Ql release .
This keyword is valid in
.Ql collection .
.It Sy port Ar number
Specifies the remote port number.
The default value is 7777.
This keyword is valid in
.Ql config .
.It Sy prefix Ar directory
Specifies the directory where files of the retrieved collection are stored.
It must be an absolute path.
This keyword is valid in
.Ql collection .
.It Sy proto, protocol Ar af
Forces
.Nm
to use an address family
.Ar af .
.Pp
The following address families are available:
.Bl -tag -width indent
.It Sy inet, inet4, ipv4
IP version 4
.It Sy inet6, ipv6
IP version 6
.El
.Pp
This keyword is valid in
.Ql config .
.It Sy refuse Ar file
Specifies a refuse file name.
Using the refuse file, the clients can specify sets of files that they does
not wish to receive.
The single pattern is permitted on each line, and files and directories
matching the patterns are neither updated nor deleted; they are simply ignored.
The patterns are interpreted by
.Xr fnmatch 3 .
This keyword is valid in
.Ql collection .
.It Sy release Ar type
Specifies a type of collections which are retrieved from the remote host.
When most of files in a collection have a specific format such as
.Xr rcsfile 5 ,
.Nm
can use optimized algorithms to transfer such files.
However, it needs that
.Ql release Ar type
is specified properly.
.Pp
Using
.Ql release Ar type ,
you can specify transfer a file tree itself in a collection or a partial
information of the tree such as a specific revision in
.Xr rcsfile 5 .
This is the reason why
.Nm
does not decide the collection type automatically.
.Pp
The following types are available:
.Bl -tag -width indent
.It Sy list
Fetch a list of available collections from the remote host.
When
.Ql name
is specified as
.Ql all
the list contains all of the collections, when specified as
.Ql rcs
the list contains collections whose type is
.Ql rcs .
See also
.Ql name .
.It Sy rcs
Fetch a collection whose type is
.Ql rcs
from the remote host.
The collection name must be specified in
.Ql name .
.El
.Pp
This keyword is valid in
.Ql collection .
.It Sy scanfile Ar file
Specifies the scanfile to store the information about a directory structure.
When a scanfile is specified,
.Nm
does not scan a directory structure and use the information from the scanfile
instead.
This allows to reduce disk i/o load radically.
This file is generated automatically if does not exist and is updated when
.Nm
is executed.
It must be an absolute path.
This keyword is valid in
.Ql collection .
.It Sy umask Ar number
Forces
.Nm
to use a umask value of
.Ar number .
The default value is 022.
This keyword is valid in
.Ql collection .
.El
.Sh URI SYNTAX
.Nm
accepts the following URI syntax in addition to the config file.
.Pp
.Bl -tag -width indent
.It cvsync://<host>[:<port>][/[<name>/<release>/][?prefix=....]]
.El
.Pp
.Bl -tag -width indent
.It Sy host
Equivalent to
.Ql host
in
.Ql config .
.It Sy port
Equivalent to
.Ql port
in
.Ql config .
When this is omitted,
.Ql 7777
is used by default.
.It Sy name
Equivalent to
.Ql name
in
.Ql collection .
When this is omitted,
.Ql all
is used by default.
.It Sy release
Equivalent to
.Ql release
in
.Ql collection .
When this is omitted,
.Ql list
is used by default.
.It Sy prefix
Equivalent to
.Ql prefix
in
.Ql collection .
This can be omitted only when
.Ql release
is specified as
.Ql list .
.El
.Pp
For example:
.Bl -tag -width indent
.It % cvsync cvsync://cvsync.example.com/
Retrieves a list of all collections from
.Ql cvsync.example.com .
This is equivalent to
.Ql cvsync://cvsync.example.com/all/list/ .
.It % cvsync cvsync://cvsync.example.com/netbsd/rcs/?prefix=/cvsroot
Retrieves
.Ql netbsd
collection from
.Ql cvsync.example.com
and store it into
.Ql /cvsroot
on the client.
The collection type is
.Ql rcs .
.El
.Sh EXAMPLES
This is a typical configuration file to update a local mirror of the NetBSD
repository:
.Bd -literal -offset indent
config {
        hostname cvsync.example.com

        collection {
                name all release list
        }
}
config {
        hostname cvsync.example.com

        collection {
                name netbsd release rcs
                prefix /cvsroot
        }
}
.Ed
.Pp
The first
.Em config
retrieves the available collection list on the remote host, and then the next
.Em config
updates the
.Ql netbsd
collection.
.Pa /cvsroot
is the directory where the repository to be stored in on the client,
and
.Em cvsync.example.com
is a hostname of the remote host.
.Sh EXIT STATUS
The
.Nm
utility exits EXIT_SUCCESS on success, and EXIT_FAILURE if an error occurs.
.Sh SEE ALSO
.Xr cvscan 1 ,
.Xr cvsyncd 1
