.\"
.\" This software is released under the BSD License, see LICENSE.
.\"
.Dd Apr 3, 2005
.Dt RCSCAN 1
.Os
.Sh NAME
.Nm rcscan
.Nd examine that files are
.Xr rcsfile 5
compliant
.Sh SYNOPSIS
.Nm rcscan
.Op Fl qv
.Ar
.Sh DESCRIPTION
.Nm
is a small utility to examine that files are
.Xr rcsfile 5
compliant.
If they are
.Xr rcsfile 5
compliant,
.Nm
print reformatted them to the standard output.
.Pp
The following options are available:
.Bl -tag -width indent
.It Fl q
Be silent mode.
.It Fl v
Be verbose mode.
.El
.Sh EXIT STATUS
The
.Nm
utility exits EXIT_SUCCESS on success, and EXIT_FAILURE if an error occurs.
.Sh SEE ALSO
.Xr rcsfile 5
