.\"
.\" Copyright (c) 2003-2012 MAEKAWA Masahide <maekawa@cvsync.org>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the author nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd Apr 10, 2004
.Dt CVSUP2CVSYNC 1
.Os
.Sh NAME
.Nm cvsup2cvsync
.Nd convert a scanfile from the CVSup style to the cvsync style.
.Sh SYNOPSIS
.Nm cvsup2cvsync
.Op Fl hqv
.Op Fl u Ar umask
.Fl i Ar CVSup-scanfile
.Fl o Ar cvsync-scanfile
.Sh DESCRIPTION
.Nm
converts a CVSup(R) scanfile into a cvsync counterpart, has been added.
When the upstream server is using CVSup and you want to redistribute the
contents using CVSync, this tool is your friend.
.Pp
The following options are available:
.Bl -tag -width indent
.It Fl h
Print the usage of
.Nm
to standard error.
.It Fl i Ar CVSup-scanfile
Specifies an input file name.
.It Fl o Ar cvsync-scanfile
Specifies an output file name.
.It Fl q
Be silent mode.
.It Fl u Ar umask
Forces
.Nm
to use a umask value of
.Ar umask .
.It Fl v
Be verbose mode.
.El
.Sh EXIT STATUS
The
.Nm
utility exits EXIT_SUCCESS on success, and EXIT_FAILURE if an error occurs.
.Sh SEE ALSO
.Xr cvscan 1 ,
.Xr cvsync2cvsup 1 ,
.Xr cvsyncd 1
